
keybinds = {
    'dart_monkey': 'q',
    'boomerang_monkey':  'w',
    'bomb_shooter':  'e',
    'tack_shooter':  'r',
    'ice_monkey':  't',
    'glue_gunner':  'y',
    'sniper_monkey':  'z',
    'monkey_sub':  'x',
    'monkey_buccaneer':  'c',
    'monkey_ace':  'v',
    'heli_pilot':  'b',
    'mortar_monkey':  'n',
    'dartling_gunner':  'm',
    'wizard_monkey':  'a',
    'super_monkey':  's',
    'ninja_monkey':  'd',
    'alchemist':  'f',
    'druid':  'g',
    'banana_farm':  'h',
    'engineer_monkey':  'l',
    'spike_factory':  'j',
    'monkey_village':  'k',
    'heroes':  'u',
    'upgrade_path_1':  ',',
    'upgrade_path_2':  '.',
    'upgrade_path_3':  '/',
    'change_targeting':  'tab',
    'reverse_change_targeting':  ['ctrl', 'tab'],
    'sell':  'backspace',
    'play':  'space',
    'fast_forward':  'space',
    'send_next_round':  ['shift', 'space'],
    'pause':  '`',
    'activated_ability_1':  '1',
    'activated_ability_2':  '2',
    'activated_ability_3':  '3',
    'activated_ability_4':  '4',
    'activated_ability_5':  '5',
    'activated_ability_6':  '6',
    'activated_ability_7':  '7',
    'activated_ability_8':  '8',
    'activated_ability_9':  '9',
    'activated_ability_10':  '0',
    'activated_ability_11':  '-',
    'activated_ability_12':  '=',
    'road_spikes':  ['shift', '1'],
    'moab_mine':  ['shift', '2'],
    'glue_trap':  ['shift', '3'],
    'camo_trap':  ['shift', '4'],
    'banana_farmer':  ['shift', '5'],
    'tech_bot':  ['shift', '6'],
    'energizing_totem':  ['shift', '7'],
    'pontoon':  ['shift', '8'],
    'portable_lake':  ['shift', '9'],
    'super_monkey_storm':  ['shift', '0'],
    'monkey_boost':  ['shift', '-'],
    'thrive':  ['shift', '='],
    'time_stop':  ['shift', '['],
    'cash_drop':  ['shift', ']'],
    'send_red_bloon':  ['control', '1'],
    'send_blue_bloon':  ['control', '2'],
    'send_green_bloon':  ['control', '3'],
    'send_yellow_bloon':  ['control', '4'],
    'send_pink_bloon':  ['control', '5'],
    'send_black_bloon':  ['control', '6'],
    'send_purple_bloon':  ['control', '7'],
    'send_white_bloon':  ['control', '8'],
    'send_lead_bloon':  ['control', '9'],
    'send_zebra_bloon':  ['control', '0'],
    'send_rainbow_bloon':  ['control', '-'],
    'send_ceramic_bloon':  ['control', '='],
    'send_moab_bloon':  ['control', '['],
    'send_bfb_bloon':  ['control', ']'],
    'send_bad_bloon':  ['control', '\\'],
    'send_test_bloon':  ['control', '`'],
}


